//cart
export const ADD_TO_CART = "[PRODUCT]ADD_TO_CART";
export const REMOVE_TO_CART = "[PRODUCT]REMOVE_TO_CART";
export const CART_PRODUCT_QUANTITY_Up = "[PRODUCT]CART_PRODUCT_QUANTITY_Up";
export const CART_PRODUCT_QUANTITY_Down = "[PRODUCT]CART_PRODUCT_QUANTITY_Down";

//Laptop
export const FECH_LAPTOP_PRODUCT_START = "FECH_LAPTOP_PRODCUT_START";
export const FECH_LAPTOP_PRODCUT_SUCCESS = "FECH_LAPTOP_PRODCUT_SUCCESS";
export const FECH_LAPTOP_PRODUCT_FAUILER = "FECH_LAPTOP_PRODUCT_FAUILER";

//LaptopBy-id
export const FECH_LAPTOP_BY_ID_START = "FECH_LAPTOP_BY_ID_START";
export const FECH_LAPTOP_BY_ID_SUCCESS = "FECH_LAPTOP_BY_ID_SUCCESS";
export const FECH_LAPTOP_BY_ID_FAUILER = "FECH_LAPTOP_BY_ID_FAUILER";

//LaptopCommmnet
export const FECH_LAPTOP_COMMNET_START = "FECH_LAPTOP_COMMNET_START";
export const FECH_LAPTOP_COMMENT_SUCCESS = "FECH_LAPTOP_COMMENT_SUCCESS";
export const FECH_LAPTOP_COMMNET_FAUILER = "FECH_LAPTOP_COMMNET_FAUILER";

//Mobile
export const FECH_MOBILE_PRODUCT_START = "FECH_MOBILE_PRODUCT_START";
export const FECH_MOBILE_PRODUCT_SUCCESS = "FECH_MOBILE_PRODUCT_SUCCESS";
export const FECH_MOBILE_PRODUCT_FAUILER = "FECH_MOBILE_PRODUCT_FAUILER";

//MobileBy-id
export const FECH_MOBILE_BY_ID_START = "FECH_MOBILE_BY_ID_START";
export const FECH_MOBILE_BY_ID_SUCCESS = "FECH_MOBILE_BY_ID_SUCCESS";
export const FECH_MOBILE_BY_ID_FAUILER = "FECH_MOBILE_BY_ID_FAUILER";

//MobileCommmnet
export const FECH_MOBILE_COMMNET_START = "FECH_MOBILE_COMMNET_START";
export const FECH_MOBILE_COMMENT_SUCCESS = "FECH_MOBILE_COMMENT_SUCCESS";
export const FECH_MOBILE_COMMNET_FAUILER = "FECH_MOBILE_COMMNET_FAUILER";

//SearchProduct
export const FECH_SEARCH_PRODUCT_START = "FECH_SEARCH_PRODUCT_START";
export const FECH_SEARCH_PRODUCT_SUCCESS = "FECH_SEARCH_PRODCUT_SUCCESS";
export const FECH_SEARCH_PRODUCT_FAUILER = "FECH_SEARCH_PRODUCT_FAUILER";

//SmartWatch
export const FECH_SMARTWATCH_PRODUCT_START = "FECH_SMARTWATCH_PRODUCT_START";
export const FECH_SMARTWATCH_PRODUCT_SUCCESS =
  "FECH_SMARTWATCH_PRODUCT_SUCCESS";
export const FECH_SMARTWATCH_PRODUCT_FAUILER =
  "FECH_SMARTWATCH_PRODUCT_FAUILER";

//SmartWatch-byid
export const FECH_SMARTWATCH_BY_ID_START = "FECH_SMARTWATCH_BY_ID_START";
export const FECH_SMARTWATCH_BY_ID_SUCCESS = "FECH_SMARTWATCH_BY_ID_SUCCESS";
export const FECH_SMARTWATCH_BY_ID_FAUILER = "FECH_SMARTWATCH_BY_ID_FAUILER";

//SmartWatchCommmnet
export const FECH_SMARTWATCH_COMMNET_START = "FECH_SMARTWATCH_COMMNET_START";
export const FECH_SMARTWATCH_COMMENT_SUCCESS = "FECH_SMARTWATCH_COMMENT_SUCCESS";
export const FECH_SMARTWATCH_COMMNET_FAUILER = "FECH_SMARTWATCH_COMMNET_FAUILER";

//GaminAccessories
export const FECH_GAMINGACCESSORIES_PRODUCT_START =
  "FECH_GAMINGACCESSORIES_PRODUCT_START";
export const FECH_GAMINGACCESSORIES_PRODUCT_SUCCESS =
  " FECH_GAMINGACCESSORIES_PRODUCT_SUCCESS";
export const FECH_GAMINGACCESSORIES_PRODUCT_FAUILER =
  "FECH_GAMINGACCESSORIES_PRODUCT_FAUILER";

//GaminAccessories-byid
export const FECH_GaminAccessories_BY_ID_START =
  "FECH_GaminAccessories_BY_ID_START";
export const FECH_GaminAccessories_BY_ID_SUCCESS =
  "FECH_GaminAccessories_BY_ID_SUCCESS";
export const FECH_GaminAccessories_BY_ID_FAUILER =
  "FECH_GaminAccessories_BY_ID_FAUILER";
